name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build_wheels:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            # tag '2023.04.15'
            vcpkgCommitId: '501db0f17ef6df184fcdbfbe0f87cde2313b6ab1'
            triplet: 'x64-linux-dynamic'
          - os: macos-latest
            # tag '2023.04.15'
            vcpkgCommitId: '501db0f17ef6df184fcdbfbe0f87cde2313b6ab1'
            triplet: 'x64-osx-dynamic'

    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}

    steps:
      - uses: actions/checkout@v3

      - name: run vcpkg
        uses: lukka/run-vcpkg@main
        id: run_vcpkg
        with:
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'
          # 'runVcpkgInstall=false' is especially important in the case of Linux -
          # we need the cibuildwheel Docker container to actually build/install
          # the dependencies, even if they are stored on the host filesystem
          # (exposed via the /host mount point) and cached by the host runner.
          runVcpkgInstall: false
          vcpkgJsonGlob: '${{ github.workspace }}/build-scripts/vcpkg.json'

      - name: List $RUNNER_WORKSPACE before build
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Prints output of run-vcpkg action.
        run: echo "root='${{ steps.run_vcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.run_vcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}' "

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.1
        env:
          CIBW_ENVIRONMENT: "SKBUILD_CONFIGURE_OPTIONS=' -DCMAKE_TOOLCHAIN_FILE=${{ runner.workspace }}/b/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} -DVCPKG_INSTALLED_DIR=${{ runner.workspace }}/b/vcpkg_installed -DVCPKG_MANIFEST_DIR=${{ github.workspace }}/build-scripts -DUPSP_BUILD_TESTING=OFF -DUPSP_BUILD_APPLICATIONS=OFF -DUPSP_BUILD_PYBIND11=ON'"
          CIBW_ENVIRONMENT_LINUX: "SKBUILD_CONFIGURE_OPTIONS=' -DCMAKE_TOOLCHAIN_FILE=/host/${{ runner.workspace }}/b/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} -DVCPKG_INSTALLED_DIR=/host/${{ runner.workspace }}/b/vcpkg_installed -DVCPKG_MANIFEST_DIR=/host/${{ github.workspace }}/build-scripts -DUPSP_BUILD_TESTING=OFF -DUPSP_BUILD_APPLICATIONS=OFF -DUPSP_BUILD_PYBIND11=ON'"
          CIBW_BUILD: "cp39-*"
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
